services:
  postgres:
    image: postgres:16
    container_name: homematch_db
    environment:
      POSTGRES_USER: homematch
      POSTGRES_PASSWORD: homematch123
      POSTGRES_DB: homematch_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: homematch_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://homematch:homematch123@postgres:5432/homematch_db
      SECRET_KEY: supersecretkey123homematch
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      STRIPE_SECRET_KEY: sk_test_TU_CLAVE_AQUI
      STRIPE_WEBHOOK_SECRET: whsec_TU_WEBHOOK_SECRET
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads

  ml-service:
    build: ./ml-service
    container_name: homematch_ml
    ports:
      - "8001:8001"
    environment:
      ML_DATABASE_URL: postgresql://homematch:homematch123@postgres:5432/homematch_db
    depends_on:
      - postgres
    volumes:
      - ./ml-service:/app

  gateway:
    build: ./gateway
    container_name: homematch_gateway
    ports:
      - "9000:9000"
    environment:
      SECRET_KEY: supersecretkey123homematch
      BACKEND_URL: http://backend:8000
      ML_URL: http://ml-service:8001
      FERNET_KEY: ${FERNET_KEY:-}
    depends_on:
      - backend
      - ml-service
    volumes:
      - ./gateway:/app

volumes:
  postgres_data:
  uploads_data: